overrides: coala.yaml

name: coala-pyflakes
description: A collection of bears implemented using pyflakes-enhanced-AST
url: https://github.com/macbox7/coala-pyflakes
author: Ankit Joshi
contact: ajankit2304@gmail.com
license: MIT
version: 0.1
release: 0.1
build_version: 0.1
package_module: pyflakes_bears
docs_output_dir: docs
ci_directory: .circleci

dependencies:
  - coala==0.12.0.dev20180101025653
  - coala-bears==0.12.0.dev20171110210444
  - pyflakes~=1.5.0

packages:
  - pyflakes_bears
  - pyflakes_generic_plugins

configuration:
  template_dir:
    - .moban.dt/
    - ../coala-mobans/templates/
    - ../coala-mobans/assets/
    - ../setupmobans/templates/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/

targets:
  - setup.py: coala-setup.py.jj2
  - pyflakes_bears/VERSION: VERSION.jj2
  - requirements.txt: requirements.txt.jj2
  - test-requirements.txt: test-requirements.txt.jj2
  - .circleci/appveyor.yml: ci/appveyor.yml.jj2
  - .circleci/run_with_env.cmd: run_with_env.cmd
