overrides: coala.yaml

name: coala-pyflakes
description: A collection of bears implemented using pyflakes-enhanced-AST
url: https://github.com/macbox7/coala-pyflakes
author: Ankit Joshi
contact: ajankit2304@gmail.com
license: MIT
version: 0.1
release: 0.1
build_version: 0.1
package_module: pyflakes_bears
docs_output_dir: docs
ci_directory: .ci
docs_source_dir: ./
docs_toc: false

dependencies:
  - coala-bears==0.12.0.dev20171110210444

packages:
  - pyflakes_bears
  - pyflakes_generic_plugins

configuration:
  template_dir:
    - .moban.dt/
    - ../coala-mobans/templates/
    - ../coala-mobans/assets/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/

copy:
  - docs-requirements.txt: docs/docs-requirements.txt
  - docs/_static/images/coala_logo.svg: docs/images/coala_logo.svg
  - docs/_static/images/coala-header.png: docs/images/coala-header.png
  - docs/.gitignore: docs/.gitignore
  - docs/Makefile: docs/Makefile
  - docs/make.bat: docs/make.bat
  - docs/_static/custom.css: docs/custom.css

targets:
  - setup.py: coala-setup.py.jj2
  - pyflakes_bears/VERSION: VERSION.jj2
  - requirements.txt: requirements.txt.jj2
  - test-requirements.txt: test-requirements.txt.jj2
